"""
core/config.py — Configuration centralisée
Toutes les variables d'environnement sont lues ici et nulle part ailleurs.
"""
from __future__ import annotations

import json
import os
import secrets
from functools import lru_cache

from dotenv import load_dotenv
from pydantic import field_validator
from pydantic_settings import BaseSettings

load_dotenv()


class Settings(BaseSettings):
    # ── Mode ───────────────────────────────────────────────────────
    use_mock_data: bool = True

    # ── GLPI ───────────────────────────────────────────────────────
    glpi_base_url: str = "http://nginx"
    glpi_app_token: str = ""
    glpi_user_token: str = ""
    glpi_verify_ssl: bool = False
    glpi_purchase_category_id: int = 0

    # ── Base de données ────────────────────────────────────────────
    database_url: str = "postgresql://dashboard:dashboard@postgres:5432/dashboard_achat"

    # ── CORS ───────────────────────────────────────────────────────
    cors_origins: list[str] = ["http://localhost:3000", "http://127.0.0.1:3000"]

    # ── Sécurité JWT ───────────────────────────────────────────────
    # Générez une valeur forte en prod : python -c "import secrets; print(secrets.token_hex(32))"
    jwt_secret: str = "change-me-in-production-use-a-long-random-secret"
    # Secret used to verify one-time tokens generated by the GLPI plugin
    glpi_plugin_secret: str = ""

    # ── Timezone ───────────────────────────────────────────────────
    tz: str = "Indian/Antananarivo"

    # ── Constantes métier GLPI ─────────────────────────────────────
    resolved_statuses: frozenset[int] = frozenset({5, 6})
    rejected_statuses: frozenset[int] = frozenset({6})
    urgent_priorities: frozenset[int] = frozenset({4, 5, 6})
    late_threshold_days: int = 5
    glpi_history_cache_ttl_seconds: int = 300

    status_map: dict[int, str] = {
        1: "Nouveau",
        2: "En cours (assigné)",
        3: "En cours (planifié)",
        4: "En attente",
        5: "Résolu",
        6: "Clos",
    }

    @field_validator("cors_origins", mode="before")
    @classmethod
    def parse_cors(cls, v: str | list) -> list[str]:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except Exception:
                return [v]
        return v

    @property
    def glpi_api_url(self) -> str:
        return f"{self.glpi_base_url.rstrip('/')}/apirest.php"

    model_config = {"env_file": ".env", "case_sensitive": False, "extra": "ignore"}


@lru_cache
def get_settings() -> Settings:
    return Settings()
